/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.*;

/**
 *
 * @author Viet Anh
 */
public class MainPage extends javax.swing.JFrame {

    static String name;
    /**
     * Creates new form HomeFrame
     */
    public MainPage(String name) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.name = name;
        this.jLabelWel.setText("Welcome " + name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelWel = new javax.swing.JLabel();
        btnAccountDetail = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        setMinimumSize(new java.awt.Dimension(327, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(327, 309));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EXPENSE TRACKER");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 40));

        jLabelWel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelWel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWel.setText("Welcome");
        jPanel1.add(jLabelWel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));

        btnAccountDetail.setBackground(new java.awt.Color(102, 0, 102));
        btnAccountDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAccountDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnAccountDetail.setText("Account Details");
        btnAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccountDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        btnDetail.setBackground(new java.awt.Color(102, 0, 102));
        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnDetail.setText("Expense Details");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, 30));

        btnManage.setBackground(new java.awt.Color(102, 0, 102));
        btnManage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManage.setForeground(new java.awt.Color(255, 255, 255));
        btnManage.setText("Manage Expense");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        jPanel1.add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 250, 30));

        btnLogout.setBackground(new java.awt.Color(102, 0, 102));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        ManageExpenseFrame mf = new ManageExpenseFrame(this, rootPaneCheckingEnabled, name);
        mf.setLocationRelativeTo(null);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrame lg = new LoginFrame();
        lg.setLocationRelativeTo(null);
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        UpdateExpenseFrame uf = new UpdateExpenseFrame(this, rootPaneCheckingEnabled, name);
        uf.setLocationRelativeTo(null);
        uf.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountDetailActionPerformed
        // TODO add your handling code here:
        UpdateUserDetails uud = new UpdateUserDetails(name);
        uud.setLocationRelativeTo(null);
        uud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountDetail;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
