/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import DAO.IOFile;
import DAO.User;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Viet Anh
 */
public class SignUpFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "anh18012003";
    private static final String dataConn = "jdbc:mysql://localhost:3306/project_cse305";
    private ArrayList<User> list = new ArrayList<>();
    IOFile iofile = new IOFile();
    String masterString = "";

    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

//    private Frame mf;
    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
//        userManagement = new UserManagement();
//        ioFile = new IOFile();
//        addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//                dispose();
//            }
//        });
    }
//    public SignUpFrame(Frame mf,String title,UserManagement managerUserManagement) {
////        super(mf,title,true);
//        initComponents();
//        
//        
//        managerUser = new UserManagement();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtComfirm2 = new javax.swing.JTextField();
        txtComfirm4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSignUpUser = new javax.swing.JTextField();
        txtSignUpPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtComfirm = new javax.swing.JTextField();
        lblNameError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtJob = new javax.swing.JTextField();
        txtDOBYear = new javax.swing.JTextField();
        txtIncome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDOBMonth = new javax.swing.JTextField();
        txtDOBDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboAccountType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        txtComfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComfirm2ActionPerformed(evt);
            }
        });

        txtComfirm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComfirm4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 550));
        setPreferredSize(new java.awt.Dimension(400, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txtSignUpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));
        jPanel1.add(txtSignUpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comfirm Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComfirmActionPerformed(evt);
            }
        });
        jPanel1.add(txtComfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, -1));

        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 10));

        lblPasswordError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, 11));

        txtFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));

        txtJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobActionPerformed(evt);
            }
        });
        jPanel1.add(txtJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));

        txtDOBYear.setText("YYYY");
        txtDOBYear.setToolTipText("aa");
        txtDOBYear.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDOBYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBYearActionPerformed(evt);
            }
        });
        jPanel1.add(txtDOBYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        txtIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIncomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fullname");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Job");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monthly Income");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtDOBMonth.setText("MM");
        txtDOBMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBMonthActionPerformed(evt);
            }
        });
        jPanel1.add(txtDOBMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        txtDOBDay.setText("DD");
        txtDOBDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBDayActionPerformed(evt);
            }
        });
        jPanel1.add(txtDOBDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 60, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, -1));

        cboAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Premium" }));
        jPanel1.add(cboAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 125, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mail");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, -1));

        btnSignUp.setBackground(new java.awt.Color(102, 0, 102));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign up");
        btnSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 90, 38));

        btnClear.setBackground(new java.awt.Color(102, 0, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, 38));

        btnExit.setBackground(new java.awt.Color(102, 0, 102));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 90, 38));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        boolean noError = true;
        boolean dif = true;

        if (txtSignUpUser.getText().equals("")) {
            this.lblNameError.setText("Fill in your username, please");
            noError = false;
            dif = false;
        } else {
            this.lblNameError.setText("");
            noError = true;
            String name = txtSignUpUser.getText();
            try {
                File file = new File("User.DAT");
                Scanner sc = new Scanner(file);
                while (sc.hasNextLine()) {
                    String data = sc.nextLine();
                    String[] info = data.split(";");
                    boolean n = false;
                    if (info[0].equals(name)) {
                        dif = false;
                        this.lblNameError.setText("Your username already exists");
                    }
                    
                }
                sc.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (noError && dif) {
            String name = txtSignUpUser.getText();
            String password1 = txtSignUpPassword.getText();
            
            
            try {
            String username1 = txtSignUpUser.getText();
            password1 = txtSignUpPassword.getText();
            String fullname = txtFullname.getText();
            String job = txtJob.getText();
            String dob = txtDOBYear.getText() + "-" + txtDOBMonth.getText() + "-" + txtDOBDay.getText();
            String income = txtIncome.getText();
            int phone = 0;
            String mail = txtMail.getText();
            String type = cboAccountType.getSelectedItem().toString();

            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("insert into user values (null,'" + username1 + "','" + fullname + "','" + dob + "','" + job + "','" + income + "','" + phone + "','" + mail + "','" + type + "')");

            pst.executeUpdate();

            pst = sqlConn.prepareStatement("insert into login values ('" + username1 + "','" + password1 + "','" + mail + "')");
            
            pst.executeUpdate();
            
            pst = sqlConn.prepareStatement("insert into limits values ('" + username1 + "','Food',null,null),('" + username1 + "','Coffee',null,null),('" + username1 + "','House Fee',null,null),('" + username1 + "','Shopping',null,null),('" + username1 + "','Education',null,null);");
            
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Signed up successfully");
            
            try {
                File myObj = new File("User.DAT");
                Scanner myReader = new Scanner(myObj);
                String allData = "";
                while (myReader.hasNextLine()) {
                    String data = myReader.nextLine();
                    allData += data + "\n";
                }
                masterString = allData;
                myReader.close();
            } catch (FileNotFoundException a) {
                a.printStackTrace();
            }
            masterString += name + ";" + password1 + "\n";
            try {
                FileWriter file = new FileWriter("User.DAT");
                file.append(masterString);
                file.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            
            LoginFrame lf = new LoginFrame();
            this.dispose();
            lf.setLocationRelativeTo(null);
            lf.setVisible(true);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
            
        }
        
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.txtSignUpUser.setText("");
        this.txtSignUpPassword.setText("");
        this.txtComfirm.setText("");
        this.txtMail.setText("");
        this.lblNameError.setText("");
        this.lblPasswordError.setText("");
        this.txtFullname.setText("");
        this.txtJob.setText("");
        this.txtDOBYear.setText("YYYY");
        this.txtDOBMonth.setText("MM");
        this.txtDOBDay.setText("DD");
        this.txtIncome.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        this.dispose();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);

    }//GEN-LAST:event_btnExitActionPerformed

    private void txtComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComfirmActionPerformed

    private void txtFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullnameActionPerformed

    private void txtComfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComfirm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComfirm2ActionPerformed

    private void txtJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobActionPerformed

    private void txtComfirm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComfirm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComfirm4ActionPerformed

    private void txtDOBYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBYearActionPerformed

    private void txtIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncomeActionPerformed

    private void txtDOBMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBMonthActionPerformed

    private void txtDOBDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBDayActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cboAccountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JTextField txtComfirm;
    private javax.swing.JTextField txtComfirm2;
    private javax.swing.JTextField txtComfirm4;
    private javax.swing.JTextField txtDOBDay;
    private javax.swing.JTextField txtDOBMonth;
    private javax.swing.JTextField txtDOBYear;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtSignUpPassword;
    private javax.swing.JTextField txtSignUpUser;
    // End of variables declaration//GEN-END:variables
}
